### PR TITLE
X64 vc cleanup and creation of x64 build targets

### PR DESCRIPTION
**Pull request by chcg**
- further cleanup of the solution and vcxproj files
 - added vs 2013 <PlatformToolset>v120_xp</PlatformToolset> for all vcxproj files
- enabled MultiProcessorCompilation, disabled incompatible otion minimal rebuild
- enabled additional SDLCheck for further compiler warnings regarding the software lifecylce
- compiler warning level 4, if appropriate
- removed unused options from solution file
- added Debug-xml-test to appveyor.yml to also test this supported config
- copied vcxproj win32 configurations for X64 and adapted
- adapted and activated x64 for appveyor builds

### CODE REVIEW

**Comment by chcg** [comment]
Further steps, not done within this PR, as not functional relevant:
- maybe rename VS2010 -> VS2013 to reflect the expected visual studio version. @bruderstein  What do you think about this?
- check and remove compiler warnings caused by deeper warning level 4
- check and remove compiler warnings from switch to VS2013, VS2015

**Comment by ffes** [comment]
Any reason why, with VS2017 in RC already, you only want to make the move from vs2010 to vs2013 and not to VS2015?

And yes, I would suggest to rename from 2010 to 2013

**Comment by chcg** [comment]
Mainly because N++ is at VS2013. With the Appveyor CI build compatibllity for VS2015 is also checked, see e.g. https://ci.appveyor.com/project/bruderstein/npppluginmanager/build/1.0.10.
It should be not problem to update the vcxproj file for newer VS version. The update uses a newer platform toolset and the remaining parts are the same.

**Comment by bruderstein** [comment]
Renaming the VS2010 project directory is something we should definitely do (it's actually a project structure I don't like, I just copied it from the N++ structure at the time). I wonder if we should just move the project sln and project files around, so they're more in line with a "standard" project layout. That should be done separately though.

There are two arguments around the VS2013/VS2015 thing:
1. Having VS2013 in the repo means people using VS2013 and VS2015 can use them, assuming a trivial conversion.
2. People on VS2015 have a hard job making changes to the project files, without checking in their VS2015 specific changes.

I'm kinda leaning towards VS2015, as that's what I've got, and it's easily installable (at least the community edition) for anyone that doesn't, and makes the workflow easier for all those with it.

Let's merge this and then we can work in project updates later.

**Comment by chcg** [comment]
@bruderstein 
Should we do the renaming still in the branch or after merging back the changes to the master?
VS2015 is also what I use typically, also VS2013 is still there.

Tested a little bit with an locally for x64 adapted PluginManagerPlugins.xml, parsing seems to work fine. Also the download and installation is ok. Let me know if I should test the updated server.

**Comment by bruderstein** [comment]
I say we merge! I've tried it out too, seems good (not tried it with x64 plugin list, but I'm assuming that's working - if it's not we'll fix it :) )

We can do further project / renaming on master / other PRs then, but the x64 work is pretty much done, I think :+1: :+1: :+1:

**Comment by chcg** [comment]
Yes, that is also my feeling. We should be at the same feature level as the x86 version.
Maybe we could store an artifact of the appveyor build for early adaptors/testers. Just a few additional lines in the appveyor.yml. Something like:

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-
        $nppPluginManagerFileName = "PluginManager.$env:PLATFORM.$env:CONFIGURATION.$env:PLATFORMTOOLSET.dll"

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "pluginManager\bin\x64\Release\PluginManager.dll" -FileName "$nppPluginManagerFileName"
        }

**Comment by bruderstein** [comment]
It would be good to do that anyway for both `Release` builds, but we can do that on master (feel free to push to master for build changes).

Right, I'm pushing merge :sparkles:

**Pull request merged**
