### PR TITLE
readme.md

### PR DESCRIPTION
**Pull request by chcg**
- Converted https://github.com/chcg/nppPluginManager/blob/master/doc/index.html to markdown format via https://domchristie.github.io/to-markdown/
-  manual adaptation for markdown format to better correlate with html input

### CODE REVIEW

**Comment by bruderstein** [comment]
This is great, but...

This means we'll need to maintain two files now. If you could add a script so that this could be done automatically, i.e. not via an online tool, but a script that can just be run as part of the release, then I'll merge it.  I'm happy for this to be a small npm project in a directory in the repo (i.e. with a `package.json` for the dependency of the conversion tool and a script to run the conversion).

It's also a good idea to rebase and not merge from the upstream repository - merging the upstream into your PR makes for a messy history that is hard to read, and adds meaningless commits. If you rebase, you'll get the same effect, but the history will be tidy and there won't be any extra merge commits.

On your branch (make sure you've not got any local changes, otherwise they'll be deleted with the script)
```
# remove the merge
git reset --hard HEAD^

# add the main repo remote if you've not got it already
git remote add upstream https://github.com/bruderstein/nppPluginManager.git
git fetch upstream

# rebase
git rebase upstream/master

# now force push your branch (force because it can't just fast forward)
git push origin master --force-with-lease
 
```
Doable?

**Comment by chcg** [comment]
I think in this case just a readme with al link to the html version (https://htmlpreview.github.io/?https://github.com/bruderstein/nppPluginManager/blob/master/doc/index.html) might make more sense.

For other options see:
https://stackoverflow.com/questions/8446218/how-to-see-an-html-page-on-github-as-a-normal-rendered-html-page-to-see-preview

What do you think?

I will cleanup my master.

**Comment by bruderstein** [comment]
I'm almost leaning towards doing it the other way - let's write the readme in markdown, and have a script to build (and probably deploy) the html (maybe automatically on commit).  Non urgent, but whilst I'm devops-ing a whole lot, a little bit more isn't going to matter much.  I'll leave this open as a reminder what needs to be done.

**Comment by chcg** [comment]
ok

**Pull request closed without merging**
