### PR TITLE
notepad++ interface files from version 7.0.0

### PR DESCRIPTION
**Pull request by chcg**
- updated notepad++ interface files with version 7.0.0 files to allow proper x64 build
- avoid compiler warning by usage of define _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES
- adaption for the changed callbacks, e.g. run_dlgProc() and usage of _hSelf instead of removed parameter hWnd

### CODE REVIEW

**Comment by NN---** [comment]
You should take files from 7.1 if there was any change there.

**Comment by saintashq** [comment]
hello, am new and pretty much noob on notepad++. How do I install this pluggin? I used it on 32bit version, which for some reason doesnt run anymore on 64bit

**Comment by BenCat07** [comment]
@saintashq i know LOL, install the 32 bit version of Notepad++:
https://notepad-plus-plus.org/repository/7.x/7.0/npp.7.Installer.exe

**Comment by chcg** [comment]
The x64 branch is the dev branch for the 64 bit version of the plugin. So there is no 64 bit version available to be bundled with n++ yet.

**Comment by saintashq** [comment]
@BenCat07 ... but, as i mentioned, 32bit isnt running anymore on my 64bit system . It was running fine before the update. Shows that its running on the background process but nothing appears on screen. Recently i tweaked with some deepsh!t services of my windows system and such and such so it may be cause of that OR i dont know -.-'. Too lazy to find out but definitely missing the usage of some of the pluggins :'(

**Pull request merged**
